export const passwordGeneratorCharacters = [
    { char: 'a', enabled: true, tags: ['lowerCase', 'vowel'] },
    { char: 'b', enabled: true, tags: ['lowerCase'] },
    { char: 'c', enabled: true, tags: ['lowerCase'] },
    { char: 'd', enabled: true, tags: ['lowerCase'] },
    { char: 'e', enabled: true, tags: ['lowerCase', 'vowel'] },
    { char: 'f', enabled: true, tags: ['lowerCase'] },
    { char: 'g', enabled: true, tags: ['lowerCase'] },
    { char: 'h', enabled: true, tags: ['lowerCase'] },
    { char: 'i', enabled: true, tags: ['lowerCase', 'vowel'] },
    { char: 'j', enabled: true, tags: ['lowerCase'] },
    { char: 'k', enabled: true, tags: ['lowerCase'] },
    { char: 'l', enabled: true, tags: ['lowerCase'] },
    { char: 'm', enabled: true, tags: ['lowerCase'] },
    { char: 'n', enabled: true, tags: ['lowerCase'] },
    { char: 'o', enabled: true, tags: ['lowerCase', 'vowel'] },
    { char: 'p', enabled: true, tags: ['lowerCase'] },
    { char: 'q', enabled: true, tags: ['lowerCase'] },
    { char: 'r', enabled: true, tags: ['lowerCase'] },
    { char: 's', enabled: true, tags: ['lowerCase'] },
    { char: 't', enabled: true, tags: ['lowerCase'] },
    { char: 'u', enabled: true, tags: ['lowerCase', 'vowel'] },
    { char: 'v', enabled: true, tags: ['lowerCase'] },
    { char: 'w', enabled: true, tags: ['lowerCase'] },
    { char: 'x', enabled: true, tags: ['lowerCase'] },
    { char: 'y', enabled: true, tags: ['lowerCase', 'vowel'] },
    { char: 'z', enabled: true, tags: ['lowerCase'] },
    { char: 'A', enabled: true, tags: ['upperCase', 'vowel'] },
    { char: 'B', enabled: true, tags: ['upperCase'] },
    { char: 'C', enabled: true, tags: ['upperCase'] },
    { char: 'D', enabled: true, tags: ['upperCase'] },
    { char: 'E', enabled: true, tags: ['upperCase', 'vowel'] },
    { char: 'F', enabled: true, tags: ['upperCase'] },
    { char: 'G', enabled: true, tags: ['upperCase'] },
    { char: 'H', enabled: true, tags: ['upperCase'] },
    { char: 'I', enabled: true, tags: ['upperCase', 'vowel'] },
    { char: 'J', enabled: true, tags: ['upperCase'] },
    { char: 'K', enabled: true, tags: ['upperCase'] },
    { char: 'L', enabled: true, tags: ['upperCase'] },
    { char: 'M', enabled: true, tags: ['upperCase'] },
    { char: 'N', enabled: true, tags: ['upperCase'] },
    { char: 'O', enabled: true, tags: ['upperCase', 'vowel'] },
    { char: 'P', enabled: true, tags: ['upperCase'] },
    { char: 'Q', enabled: true, tags: ['upperCase'] },
    { char: 'R', enabled: true, tags: ['upperCase'] },
    { char: 'S', enabled: true, tags: ['upperCase'] },
    { char: 'T', enabled: true, tags: ['upperCase'] },
    { char: 'U', enabled: true, tags: ['upperCase', 'vowel'] },
    { char: 'V', enabled: true, tags: ['upperCase'] },
    { char: 'W', enabled: true, tags: ['upperCase'] },
    { char: 'X', enabled: true, tags: ['upperCase'] },
    { char: 'Y', enabled: true, tags: ['upperCase', 'vowel'] },
    { char: 'Z', enabled: true, tags: ['upperCase'] },
    { char: '0', enabled: true, tags: ['number'] },
    { char: '1', enabled: true, tags: ['number'] },
    { char: '2', enabled: true, tags: ['number'] },
    { char: '3', enabled: true, tags: ['number'] },
    { char: '4', enabled: true, tags: ['number'] },
    { char: '5', enabled: true, tags: ['number'] },
    { char: '6', enabled: true, tags: ['number'] },
    { char: '7', enabled: true, tags: ['number'] },
    { char: '8', enabled: true, tags: ['number'] },
    { char: '9', enabled: true, tags: ['number'] },
    { char: '!', enabled: true, tags: ['symbol'] },
    { char: '@', enabled: true, tags: ['symbol'] },
    { char: '#', enabled: true, tags: ['symbol'] },
    { char: '$', enabled: true, tags: ['symbol'] },
    { char: '%', enabled: true, tags: ['symbol'] },
    { char: '^', enabled: true, tags: ['symbol'] },
    { char: '&', enabled: true, tags: ['symbol'] },
    { char: '*', enabled: true, tags: ['symbol', 'arithmetic'] },
    { char: '(', enabled: true, tags: ['ambiguous'] },
    { char: ')', enabled: true, tags: ['ambiguous'] },
    { char: '-', enabled: true, tags: ['ambiguous', 'arithmetic'] },
    { char: '_', enabled: true, tags: ['ambiguous'] },
    { char: '=', enabled: true, tags: ['ambiguous', 'arithmetic'] },
    { char: '+', enabled: true, tags: ['ambiguous', 'arithmetic'] },
    { char: '`', enabled: true, tags: ['ambiguous'] },
    { char: '~', enabled: true, tags: ['ambiguous'] },
    { char: '[', enabled: true, tags: ['ambiguous', 'bracket'] },
    { char: ']', enabled: true, tags: ['ambiguous', 'bracket'] },
    { char: '{', enabled: true, tags: ['ambiguous', 'bracket'] },
    { char: '}', enabled: true, tags: ['ambiguous', 'bracket'] },
    { char: '|', enabled: true, tags: ['ambiguous'] },
    { char: ';', enabled: true, tags: ['ambiguous'] },
    { char: ':', enabled: true, tags: ['ambiguous'] },
    { char: '<', enabled: true, tags: ['ambiguous', 'arithmetic'] },
    { char: '>', enabled: true, tags: ['ambiguous', 'arithmetic'] },
    { char: "'", enabled: true, tags: ['ambiguous'] },
    { char: '.', enabled: true, tags: ['ambiguous'] },
    { char: '/', enabled: true, tags: ['ambiguous', 'arithmetic'] },
    { char: '?', enabled: true, tags: ['symbol']}
];